%% Team A

close all; clear; clc;


%% Code

addpath CarpetPlotFuncsModded\


%% Varied for carpet

nref = 3;

% Range of wing loadings

EWFstuff = linspace(0.22,0.36,1 + (nref + 1) * 7);

% Range of aspect ratios

sfcInter = linspace(0.335,0.395,1 + (nref + 1) * 4);

%% Fixed mission parameters

dist1 = 14000;

%
rangeDes = 20291;

%
bregTypes = [1,2];

dists = [dist1;rangeDes - dist1];

%
veloTAS = [102-6.5;102-6.5];

%
vWind = [6.5;6.5];

%
alt = [2500;20000];

%
wPayload = 700;

wRF = 245;

WS = 29;

EWF = 0.342;

eta = 0.8;

AR = 27;

osw = 0.8;

CD0 = 0.0160;

[X_WS,Y_AR] = meshgrid(EWFstuff,sfcInter);

z = X_WS .* 0;
SFCs = [sfcInter;sfcInter];
for i = 1:length(EWFstuff)

    for j = 1:length(sfcInter)

        try
        [Result] = weightFromSegments(bregTypes,dists,veloTAS,vWind,alt,SFCs(:,j),...
            wPayload,wRF,WS,EWFstuff(i),eta,AR,osw,CD0);

        [xMission,vTASMission,vGrndMission,wMission,rhoMission,CLMission,LDMission...
            ,pShaftMission] = missionProfileSegments3(100,[1,1],bregTypes,Result(1),...
            Result(2:end,1),dists,veloTAS,vWind,alt,SFCs(:,j),WS,EWFstuff(i),eta,AR,osw,CD0);

        close all;
        LDavg = sum((LDMission(1:end-1) + LDMission(2:end)) ./ 2 .* (xMission(2:end) - xMission(1:end-1))) / rangeDes;

         z(j,i) = Result(1);
        catch
       
        z(j,i) = nan;

        end

    end
    
end

%%
carpetMod2(Y_AR,X_WS,z,-0.30,nref,"red","blue",LineWidth=1.5);
set(gca, 'XTick', []) % Remove xticks
grid on % Turn on grid
set(gca,'FontName','Calibri','FontSize',12)
ylim([2000,13000])
ylabel("MTOW [lbs]")


%% Functions

function h = carpetMod2(x1, x2, y, offset, nref, linspec1, linspec2, varargin)
%CARPET Plots a carpet plot with two independent and one dependent variable.
%   h = carpet(x1, x2, y, offset) generates a carpet plot with
%   independent variables x1 & x2 and dependent variable y.  The plot is
%   created using a cheater axis generated by the equation:
%
%   xcheat = x1 + x2 * offset.
%
%   x1 & x2 may be vectors, or they may be matrices as generated by
%   MESHGRID.  x1, x2, & y should be arranged such that they could be
%   plotted with SURF(x1,x2,y).
%
%   Handles to the resulting carpet plot curves are returned in h.
%
%   Setting nonzero nref will cause lines in the carpet plot to be skipped.
%   This can be used to create smooth curves in the carpet plot without
%   excess clutter.  Default nref = 0.  The same value of nref is applied
%   to both x1 and x2 directions.  Refined vectors can be created using
%   REFVEC.
%
%   linspec1 specifies the line style for the x1=constant lines.  If it is
%   not specified, it defaults to 'k'.
%
%   linspec2 specifies the line style for the x2=constant lines.  If it is
%   not specified, it defaults to linspec1.
%
%   Any additional arguments passed to CARPET are passed to the plot
%   command.
%
%   See also CARPETCONVERT, CARPETCONTOURCONVERT, REFVEC.

%   Rob McDonald 
%   ramcdona@calpoly.edu  
%   19 February 2013 v. 1.0

if( nargin < 5 )
  nref = 0;
end

% Handle default line styles.
if( nargin < 6 )
  linspec1 = 'k';
end

if( nargin < 7 )
  linspec2 = linspec1;
end

% If input is not matrix similar to meshgrid, make it so.
if( isvector(x1) && isvector(x2) )
  [X1,X2] = meshgrid( x1, x2 );
else
  X1 = x1;
  X2 = x2;
end

% Calculate the cheater axis.
Xcheat = X1 + X2 * offset;

% Plot the carpet plot lines.
figure();
hold on
plot(Xcheat(1:nref+1:end,:)', y(1:nref+1:end,:)',...
    varargin{:}, Color=linspec1)
plot(Xcheat(:,1:nref+1:end), y(:,1:nref+1:end), ...
    varargin{:}, Color=linspec2);
% Hide the X-axis and turn off the box.
ca = gca;
set(ca,'XTick',[])
box off
set(ca,'XColor',[1,1,1])
end



